### ISSUE TITLE
Sync recent updates to npm

### ISSUE THREAD

**Issue by bpartridge83** [logdna/nodejs#1]
The README mentions `createLogger`, but the most recent version from npm doesn't work as described. The optional params (mac, IP, etc) would be helpful, as well.

**Comment by respectus** [comment]
Hi @bpartridge83, thanks for bringing this up. I've updated the version on npm and I've corrected the README to state that the MAC/IP and hostname fields are now all optional. Please let me know if the `createLogger` function (or the rest of the logdna module) are not functioning as described in the README.
