### ISSUE TITLE
No meta object without "index_meta: true" but parsing error with "index_meta: true" if meta object contains "data"-key 

### ISSUE THREAD

**Issue by rrutsche** [logdna/nodejs#100]
These are actually two issues:

**First one** - we cannot see a meta object in the logs if we don't set `index_meta` to `true`. This worked before with the same setup.

How to reproduce:
```
createLogger("123123123", {
    app: "test-service",
    hostname: "path.to.host.com",
    env: "localhost"
})
logger.log("Hello Log", { 
    meta: {
        foo: "bar"
    }
})
```

**Second one** - setting `index_meta` to `true` solves the behaviour described above. But it produces a parsing error if the meta object contains an object called `data`.

How to reproduce:
```
createLogger("123123123", {
    app: "test-service",
    hostname: "path.to.host.com",
    env: "localhost",
    index_meta: true
})
logger.log("Hello Log", { 
    meta: {
        data: {
            foo: "bar"
        }
    }
})
```

**Comment by matt-march** [comment]
Thanks for reporting these issues @rrutsche . I can reproduce the first issue and am following up to figure out what's happening there. 

I'm currently unable to reproduce the second issue. Can you let me know: 
- Which version of the nodejs client you're using
- Where you're getting the parsing error

**Comment by dkMorlok** [comment]
Confirm, first issue is reproducible. 
If i try to send "data" in meta there is no problem. I can see logs in web application.

**Comment by rrutsche** [comment]
Hi @matt-march thanks for your response, 
We are using version `3.5.1`. The parsing error is visible in the log view, after expanding the log in the dashboard. In this case data was just an empty object. It occurred in combination with `index_meta: true`.

![Screenshot 2020-07-29 at 15 32 19](https://user-images.githubusercontent.com/1104171/88806483-c7843100-d1b0-11ea-84cb-b79209f936ff.png)

**Comment by matt-march** [comment]
Hi @rrutsche we've got a fix for issue 1 waiting to be released. Issue 2 will require some more digging.

**Comment by rrutsche** [comment]
Awesome. Thanks a lot.

**Comment by matt-march** [comment]
Hi again @rrutsche. The fix for issue 1 should be released now.

**Comment by darinspivey** [comment]
@rrutsche, gonna close out this as it appears to be resolved.  Also, our new client has been released, so you may want to upgrade.  Please refer to the README in our new package, [@logdna/logger](https://www.npmjs.com/package/@logdna/logger)

Feel free to open any issues under that new repository.  Thanks!
