### ISSUE TITLE
Add option to only print out logs in the console

### ISSUE THREAD

**Issue by hamboomger** [logdna/nodejs#108]
Is there a way to NOT send out the logs to the LogDNA platform and just print them in the console? Basically I don't want to send out logs in test or local environment, but I still want to see them in the console.

**Comment by darinspivey** [comment]
Hi!  Thanks for submitting an issue, however [this project was deprecated](https://github.com/logdna/nodejs#deprecation-notice) over a year ago.  You should seriously consider upgrading to our supported logger, `@logdna/logger`.

That being said, your request is a bit confusing.  The node logger doesn't log anything to `console`, but if you're suggesting to add that, and to have it be turned on/off as desired, then that doesn't feel like the responsibility of this logger.    

It sounds as if you want a simple wrapper around our logger.  Here's some rough code that might get you started, and hopefully this will help nudge you to upgrade to `@logdna/logger` ;)

```js
'use strict'

const {createLogger} = require('@logdna/logger')
const {LOG_LEVELS} = require('@logdna/logger/lib/constants')

class MyLogWrapper {
  constructor(env, opts) {
    this.logger = null
    if (env === 'production') {
      this.logger = createLogger('YOURKEYHERE', opts)
    }
    for (const level of LOG_LEVELS) {
      const lower_level = level.toLowerCase()
      Object.defineProperties(this, {
        [lower_level]: {
          enumerable: true
        , writable: false
        , configurable: false
        , value(...args) {
            if (!this.logger) {
              console.log(`[${level}] `, ...args)
              return
            }
            this.logger[lower_level](...args)
          }
        }
      })
    }
  }
}

const log = new MyLogWrapper(process.env.NODE_ENV)
log.info('Here is an info line')
log.trace('here is a trace')
log.error({error: new Error('some error')})
```

**Comment by hamboomger** [comment]
@darinspivey maan this is so dumb, I accidentally left an issue here instead of the `@logdna/logger` one. Big props for using the `@logdna/logger` dep in your response anyways, I'll try it out in my scenario :) Really appreciate your response!

**Comment by hamboomger** [comment]
Oh, but you are also one of the main contributors for the `@logdna/logger` repository, so I guess your response was actually about the `@logdna/logger`, right?

**Comment by darinspivey** [comment]
That is correct. We are no longer supporting the old one as it is deprecated. Glad we could help. Good luck! Feel free to close this issue if you feel that this is sufficient.

**Comment by darinspivey** [comment]
Just to add some more notes for anyone else that might read this, our logger is not a true  console "logger" that respects log levels during output. It's specifically for our platform, and we ingest all lines regardless of level. So, you may want to replace console.log with something like pino, which would respect the log level and only print if necessary. That would be more one-to-one with what you're looking for.
