### ISSUE TITLE
Node exiting prematurely in 1.2.9

### ISSUE THREAD

**Issue by gigafied** [logdna/nodejs#16]
This is a pretty big deal for me, see comment here: https://github.com/logdna/nodejs/commit/a14e1245a91e9c0e7493e0c6a38f547409ebca1b#diff-212f63e53d7aa8ed04659d1cabd48137R210

**Comment by respectus** [comment]
Hey appreciate you reporting this. Sorry for the inconvenience, it was a terrible assumption on my part to call process.exit. I've released a new patch which removes the lines in question. Thanks for catching this, please do let me know if you have any issues with version 1.2.10.
