### ISSUE TITLE
SIGINT handler causes process to hang when interrupted

### ISSUE THREAD

**Issue by cwp** [logdna/nodejs#18]
Flushing logs on SIGINT and SIGTERM is a nice idea, but since you don't then call `process.exit()` the node process hangs after the logs have been flushed:

https://github.com/logdna/nodejs/blob/master/lib/logger.js#L232

Of course, calling `process.exit()` will also be a problem, because if an app registers its own handler, that probably won't get called since logdna is exiting before the app's handler gets to run.

You could be clever, and see if there are any handlers that are supposed to run after yours, or just make it another configuration option. Either way, you probably shouldn't register the handler if no loggers are configured to flush anyway.

**Comment by respectus** [comment]
Hi @cwp , FWIW I agree with you that we should probably not be registering any handlers, and we should just expose a cleanup/flush logs function. A user that wants to flush logs on SIGTERM or SIGINT can do so themselves by calling the cleanup function in their own handler. However, I believe the latest changes in version 1.3.3 attempt to perform a cleanup and then call all other handlers, after which it calls process.exit() itself. If someone else decides to call process.exit() in their handler, then there isn't any guarantee that our cleanup function would be called. I'm hoping that version 1.3.3 will work for most use cases so we are going forward with it. If version 1.3.3 causes issues then I will probably revert to not using any handlers, instead our users will have to opt in and setup their own handler to call the cleanup function. Really appreciate your feedback on this module, please do let me know if you have any suggestions for improvement, Thanks!
