### ISSUE TITLE
`create` vs `createLogger`

### ISSUE THREAD

**Issue by bpartridge83** [logdna/nodejs#2]
The `createLogger` function is returned from `lib/logger.js`, but it's being assigned to the global space as `create`:

https://github.com/logdna/nodejs/blob/master/index.js#L2

So, this fails:

```
const Logger = require('logdna');
let logger = Logger.createLogger(...
```

But `Logger.create` is working as `createLogger` is documented.

**Comment by respectus** [comment]
Ah I see, thanks for catching that. I should have tested the module as found on npm. I have edited the index.js file to properly expose the name `createLogger` in the global space. I appreciate the feedback, please don't hesitate to let me know any other improvements I can make. Thanks Brian!
