### ISSUE TITLE
SIGINT and SIGTERM don't seem to be working, even after fix

### ISSUE THREAD

**Issue by 0505gonzalez** [logdna/nodejs#22]
Logdna keeps our server alive after we try to terminate with SIGINT. Here's Why we think it occurs (steps 1, 2, 3):

```
function onSignal(sigType) {
    var i = loggers.length;
    var finalize = process.listenerCount(sigType) > 1 ? function() {} : function() { process.exit(); };

    var expectedCallbacks = 0; // Step 1: expectedCallbacks set to zero
    function callback() {
        if (expectedCallbacks-- < 1) finalize(); // Step 3: expectedCallbacks is 1. Decrement is post fix, so comparison is if (1 < 1) which will always be false. finalize is not called
    };
    while (i--) {
        if (loggers[i][sigType]) {
            expectedCallbacks++; // Step 2: expectedCallbacks is set to 1
            loggers[i].logger._cleanUp(callback);
        }
    }
}

process.on('SIGTERM', onSignal.bind(null, 'SIGTERM'));
process.on('SIGINT', onSignal.bind(null, 'SIGINT'));
```

Is there something I'm missing? https://github.com/logdna/nodejs/blob/master/lib/logger.js#L244

**Comment by respectus** [comment]
Hi @0505gonzalez,
     We've made the decision to remove listening on signals since so many of our users are having issues. The library still exposes a cleanUpAll and cleanUp function, which users can opt-in to using if they so wish. Appreciate the feedback, do let me know if you experience any issues with logdna version 1.4.0, thanks!
