### ISSUE TITLE
Sequelize raw object not logged and freezes the whole application

### ISSUE THREAD

**Issue by gvko** [logdna/nodejs#24]
**Node.js:** `8.9.1`
**logdna:** `^1.4.0`
**bunyan:** `^1.8.12`
**logdna module part:** `BunyanStream`
**sequelize:** `^4.8.4`

**How to reproduce:**
1. Run an application where you use Bunyan and LogDNA's `BunyanStream` sub-module to log, and Sequelize for DB connection.
2. Try log a raw, unformatted Sequelize object

**What happens:**
The log is not executed (the information is not logged and does not reach LogDNA).
The server app freezes.

**More info:**
So, this is the unformatted Sequelize object that is trying to get logged:
```
[ registration {
    dataValues:
     { id: '1',
       customerId: '1',
       date: '2017-10-10',
       userId: '1',
       amount: 1800,
       unit: 'kg',
       currency: 'DKK',
       kgPerLiter: 15,
       cost: '5000',
       comment: 'Hello test',
       manual: true,
       scale: 'true',
       updatedAt: 2017-10-09T10:30:42.000Z,
       createdAt: 2017-10-09T10:30:42.000Z,
       deletedAt: null,
       areaId: '2',
       productId: '2',
       area_id: '2',
       product_id: '2' },
    _previousDataValues:
     { id: '1',
       customerId: '1',
       date: '2017-10-10',
       userId: '1',
       amount: 1800,
       unit: 'kg',
       currency: 'DKK',
       kgPerLiter: 15,
       cost: '5000',
       comment: 'Hello test',
       manual: true,
       scale: 'true',
       updatedAt: 2017-10-09T10:30:42.000Z,
       createdAt: 2017-10-09T10:30:42.000Z,
       deletedAt: null,
       areaId: '2',
       productId: '2',
       area_id: '2',
       product_id: '2' },
    _changed: {},
    _modelOptions:
     { timestamps: true,
       validate: {},
       freezeTableName: true,
       underscored: false,
       underscoredAll: false,
       paranoid: true,
       rejectOnEmpty: false,
       whereCollection: [Object],
       schema: null,
       schemaDelimiter: '',
       defaultScope: {},
       scopes: [],
       hooks: {},
       indexes: [Object],
       name: [Object],
       omitNull: false,
       getterMethods: [Object],
       sequelize: [Object],
       uniqueKeys: {} },
    _options:
     { isNewRecord: false,
       _schema: null,
       _schemaDelimiter: '',
       raw: true,
       attributes: [Object] },
    __eagerlyLoadedAssociations: [],
    isNewRecord: false } ]
```

It does not get logged and the whole app freezes, becoming unresponsive to further requests.
Nevertheless, if I format the object into the actual thing that has to be logged:
```
[
    {
        "date": "2017-10-10",
        "createdAt": "2017-10-09 10:30:42",
        "updatedAt": "2017-10-09 10:30:42",
        "id": "1",
        "customerId": "1",
        "userId": "1",
        "amount": 1800,
        "unit": "kg",
        "currency": "DKK",
        "kgPerLiter": 15,
        "cost": "5000",
        "comment": "Hello test",
        "manual": true,
        "scale": "true",
        "deletedAt": null,
        "areaId": "2",
        "productId": "2",
        "area_id": "2",
        "product_id": "2"
    }
]
```

Then it works all fine.

Of course, I don't want to log the unformatted object, because it contains a lot of redundant data, and I am going to format my objects before logging them.
I just thought it'd be nice to let you know about this issue.

**Comment by respectus** [comment]
Hi @galioy, 

Thanks for bringing this issue up, I've split the bunyan functionality out of this library and it has moved over to logdna-bunyan. Could you try logdna-bunyan out and let me know if you continue to experience the issue described above? If the issue persists we can put it in the logdna-bunyan repo and we'll continue to debug there, thanks!

**Comment by gvko** [comment]
@respectus I upgraded to `logdna-bunyan` and tested the issue and it is still present. I'll open the issue in the `logdna-bunyan` repo. :)
