### ISSUE TITLE
latest 1.4.1 does not work with Node < 6+

### ISSUE THREAD

**Issue by stringbeans** [logdna/nodejs#25]
the latest update 1.4.1 does not work in versions of Node below 6x. We are currently using Node 5.12 and logdna fails due to calls to process.emitWarning (this does not exist in Node 5)

**Comment by respectus** [comment]
Hi @stringbeans, 
Thanks for bringing this issue up. I've added a check around the call, so I believe version 1.4.2 will work as expected. We need to issue a Deprecation Warning before we bring in our next major version. Unfortunately this may have affected setups below Node 6x, apologies for the inconvenience. Please do let me know if version 1.4.2 is still causing problems, thanks!

**Comment by stringbeans** [comment]
@respectus thanks for the quick response! ive seen some repos using the `engine` attribute in the package.json to let users know what engines are supported... so in this case you could just set that attribute to be >= 6
