### ISSUE TITLE
Is the lodash dependency really needed?

### ISSUE THREAD

**Issue by adamreisnz** [logdna/nodejs#27]
I've quickly browsed through the code, does this library really need the lodash dependency to do some simple [isString checks](https://github.com/logdna/nodejs/blob/master/lib/logger.js#L25) and to [bind a function to a context](https://github.com/logdna/nodejs/blob/master/lib/logger.js#L171)?

It'd be good to clean this up and remove the dependency in the next major version.

**Comment by respectus** [comment]
Hi @adamreisnz, 

Thanks for bringing this issue up. I've removed the lodash dependency, the isString checks were easy enough to replace, but I did like the isEqual, bind functions so I've imported those. Version 2.0.0 of this module should have less unnecessary dependencies. Do let me know if you experience any issues with the latest version, thanks!

**Comment by adamreisnz** [comment]
@respectus thanks for releasing a new version and looking into this, I'll take it for a spin shortly!
