### ISSUE TITLE
Repo naming is a bit confusing

### ISSUE THREAD

**Issue by html5cat** [logdna/nodejs#28]
Right now it says "Fork Node.js", "Fork Ruby", but IMHO it would be better to have LogDNA in the repo name. It might seem repetitive but would make it more clear and better SEO :) 

Cheers!

<img width="232" alt="screen shot 2018-02-23 at 3 43 28 pm" src="https://user-images.githubusercontent.com/823890/36622114-65d9ad9c-18b0-11e8-836b-70f177616180.png">

**Comment by sethlivingston** [comment]
Agreed, and I don't have any interest or need in forking your library right now anyway. :)

**Comment by respectus** [comment]
Appreciate the suggestions, the web team has been informed. I'm going to close the issue on this repo, since it is not directly related to the functionality of the library. Thanks for the feedback!
