### ISSUE TITLE
Ambient meta

### ISSUE THREAD

**Issue by sethlivingston** [logdna/nodejs#29]
It would be really helpful to be able to add ambient meta properties to logs, a la Serilog. For example, when handling an incoming HTTP request, it would be great to give that request a correlation ID and have all further logging that occurs on that request include that correlation ID.

**Comment by smusali** [comment]
Hi, @sethlivingston, sorry for late response!

Can you give us example for what you would like to see? Thanks in advance!

**Comment by sethlivingston** [comment]
It's been a long time since I've used your Node library, but here's the (pseudocode) gist of it:

In the middleware for an incoming request, I can generate a "request ID" and attach it to the log:

    rid = generateRequestId()
    log.addProperty(rid)

Now, anytime I use that log, it will emit the request ID without me explicitly having to pass the value throughout my app.

    log.warning(...)  // automatically includes the request ID as an "ambient property"

Hope this helps.

**Comment by smusali** [comment]
Hi @sethlivingston again,

It's been added in #60 and going to be available in the upcoming release (`v3.3.0`). We will let you know once released.

Thanks for your patience!
