### ISSUE TITLE
this.log is not a function

### ISSUE THREAD

**Issue by krazyjakee** [logdna/nodejs#34]
Logdna v2.0.2
I get this error when running on node:alpine docker container (node 9.x)

```
at Logger.(anonymous function) (/node_modules/logdna/lib/logger.js:230:14)
UnhandledPromiseRejectionWarning: TypeError: this.log is not a function
```

Any idea why this could be happening?

**Comment by respectus** [comment]
Hi @krazyjakee, 
     Appreciate you reporting this issue, I believe this error may be a result of your node version and the es5 syntax used in the library. Interestingly enough we haven't had any complaints yet for an issue with node 9.x. If any node 9.x users could chime in with their experience it would be helpful. 

We want to support as many node versions as we can, including many of the older versions, which leads to some difficulty in resolving these types of issues. We're going to have a chat internally today about doing a major version bump with es6 syntax, or we might try a quick fix if we find one. Thanks!

**Comment by smusali** [comment]
@krazyjakee, are you still having this issue?
