### ISSUE TITLE
flushAll callback never called

### ISSUE THREAD

**Issue by dansgithubuser** [logdna/nodejs#37]
https://github.com/logdna/nodejs/blob/master/lib/logger.js#L238

should be `if (--expectedCallbacks < 1) cb();` or `if (expectedCallbacks-- <= 1) cb();`

**Comment by respectus** [comment]
Hmm that's weird what version of node are you using? I haven't tested this flushAll extensively, I've pushed a fix to npm logdna version 2.0.4. Do let me know if that works, thanks.

**Comment by dansgithubuser** [comment]
Was using version 2.0.2. All seems in order now. Thanks for the fast response!
