### ISSUE TITLE
Not logging JSON objects attached to winston log events

### ISSUE THREAD

**Issue by grassick** [logdna/nodejs#4]
I get one single line (the message) without the JSON objects included

e.g.

![image](https://cloud.githubusercontent.com/assets/1238335/18103444/a42c440c-6ec4-11e6-8c4b-ec57b9dfc383.png)

Each line of the PATCH has tons of JSON that isn't being logged.

(May I add that the low contrast is incredibly hard to read, also)

**Comment by respectus** [comment]
Hi @grassick , we recently added support for logging JSON objects through winston. I've updated the module on npm. Are you using the latest release? If you are experiencing these issues with release 1.1.1, then could I get your account name? I will attempt to look into the issue for you. Thanks!

**Comment by leeliu** [comment]
@grassick You can always change the color scheme by clicking on the Gear icon, then User Preferences.

![unknown](https://cloud.githubusercontent.com/assets/1399797/18106403/66c625f8-6eb8-11e6-8783-b8eea111ddf5.png)

**Comment by grassick** [comment]
Still nothing on 1.1.1. Account name is mWater (development at mwater dot co).

I tried changing themes, but low-contrast seems to be my fate. Perhaps a rendering issue with Lucida font on Linux?

**Comment by respectus** [comment]
@grassick, Thanks for bearing with us through this. I believe I have resolved the issue in release 1.1.3 on npm. Sorry for being the guinea pig on this, but we appreciate your feedback. You are helping us improve the product! Also as a side note, you can increase the font in the Log Format viewer if that helps. Please let me know if the latest npm release has resolved your issue, thanks again! Also I was wondering if your line truncation issue is resolved with the optional param max_length?
