### ISSUE TITLE
Doesn't work on Zeit's NOW

### ISSUE THREAD

**Issue by pariola** [logdna/nodejs#42]
I used LogDNA on a Now lambda and after the functions are executed, logs don't show because the function executed completely and the logs aren't pushed. I had to add a delay of 5s for this to work.

Initial Code
```js
const Logger = require("logdna");

const options = {
  hostname: "app",
  ip: "10.1.1.1",
  app: "pp"
};

const log = Logger.setupDefaultLogger(
  "KEY",
  options
);

module.exports = async (req, res) => {
  log.info(`${req.method} request`);
  res.end("OK");
};
```
Fix
```js
const Logger = require("logdna");

const options = {
  hostname: "app",
  ip: "10.1.1.1",
  app: "pp"
};

const log = Logger.setupDefaultLogger(
  "KEY",
  options
);

module.exports = async (req, res) => {
  log.info(`${req.method} request`);
  await delay();
  res.end("OK");
};

const delay = async () => {
  await sleep(5000);
};
```

also would like to know if the log functions could return a Promise.

**Comment by exwyezed** [comment]
I'm using zeit.co (v1 here) and I'm experiencing the same issue, logs don't show on LogDNA's dashboard.

**Comment by pariola** [comment]
@alfonmga Problem is because in **now.sh** the function already finished executing and LogDNA's `flushAll` function hasn't executed yet. So workaround i used was to call the `flushAll` function before sending a response.

**Comment by johnrjj** [comment]
This is still an issue.

**Comment by pnavarrc** [comment]
Confirmed, this is still an issue. I tried calling `flushAll` before sending the response and they are not getting to LogDNA. I set `NODE_DEBUG=logdna` to diagnose the issue and I'm getting the following logs:

```
2019-10-05T00:15:08.181Z 91256ee4-f052-477a-800d-d830ff4cf81b ERROR LOGDNA 8: Buffering message: pong
2019-10-05T00:15:08.181Z 91256ee4-f052-477a-800d-d830ff4cf81b ERROR LOGDNA 8: No scheduled flush. Scheduling for 250 ms from now.
Duration: 4.64 ms  Billed Duration: 100 ms  Memory Size: 3008 MB  Max Memory Used: 87 MB	
```

This is what I tried. I do get the response, but the log doesn't appear in the LogDNA dashboard

```js
import Logger from "logdna";

// Set the options...
const logger = Logger.createLogger(LOGDNA_KEY, options);
const flushAll = Logger.flushAll;

export default (req, res) => {
  logger.debug("pong", { meta: req.body });
  flushAll(() => {
    res.status(200).json(req.body);
  });
};
```

**Comment by guidolodetti** [comment]
Hi @pnavarrc! I was experiencing the same problems. I looked into the library code and I have found a bug which caused the `flushAll` callback to be called immediately instead of waiting for all the loggers to be flushed. I have made a pull request (#76) to fix the bug.

Meanwhile, if you are using a single logger you can do the following. Add a new `flush` function to the logger object:
```javascript
import logdna from 'logdna'
const logger = logdna.createLogger(LOGDNA_KEY, options)
logger.flush = () => {
    return new Promise(resolve => {
        logger._flush(err => {
            resolve()
        })
    })
}
```

With that modification you can then do the following:
```javascript
await logger.flush()
// Logs were sent!
res.status(200).json(req.body);
```
or
```javascript
logger.flush().then(() => {
    // Logs were sent!
    res.status(200).json(req.body);
})
```

**Comment by pnavarrc** [comment]
Hi @guidolodetti! I implemented something like that on my logger module, I will wait for the next release and confirm if it works well. Thanks!
