### ISSUE TITLE
Can't use from browser-based applications

### ISSUE THREAD

**Issue by chrisrichard** [logdna/nodejs#43]
Now that LogDNA supports whitelisting of CORS domains, enabling ingesting logs directly from the browser, it would be great if this package also supported Browser-based applications via Webpack or Browserify.

I hacked something in to prove it could work but killed the server implementation in the process and wasn't sure the best way to support both between trying to use isomorphic-fetch or handling the two cases separately. Either way will require some refactoring but would like to get some advice from the maintainers if possible, particularly if there are any changes already planned for this lib.

**Comment by respectus** [comment]
LogDNA version 3.0.0 uses isomorphic-fetch, I believe it can be used with Browserify now.
