### ISSUE TITLE
tags array type  throw an error

### ISSUE THREAD

**Issue by ghost** [logdna/nodejs#47]
in readme:

```javascript
// Add tags in array or comma-separated string format:
options.tags = ['logging', 'nodejs', 'logdna'];
// or:
options.tags = 'logging,nodejs,logdna';
```

in code all options are checked by the function `checkParam` which throw an error if `typeof param !== 'string'`

This option should not be checked by `checkParam` just like other options type (cf `index_meta` for example).

**Comment by smusali** [comment]
Hey @thorinisme,

Thanks for reporting this!

We are going to fix this as soon as possible!

**Comment by smusali** [comment]
@thorinisme, done in `v3.0.2`!
