### ISSUE TITLE
Truncating log messages

### ISSUE THREAD

**Issue by grassick** [logdna/nodejs#5]
We have very long messages at times that get truncated in the log viewer:

![image](https://cloud.githubusercontent.com/assets/1238335/18103507/e9bf25a2-6ec4-11e6-9fd4-e7c9c51163eb.png)

Is there a way to turn that off?

**Comment by respectus** [comment]
Hi @grassick , thanks for your feedback! Currently the npm module doesn't have the ability to stop the truncation. However, if you pull the code in this repo, and run it locally you can have greater control. Specifically if you look at lib/configs.js there is a constant MAX_LINE_LENGTH, currently this is set to 32000, but you can change this to fit your use case. If you'd like to remove the truncation completely you can remove the appropriate if statement in the _bufferLog function. I've updated the module to add an optional parameter for max_length. So if you set options.max_length = false, then no lines will be truncated. Please let me know if you have any other concerns!
