### ISSUE TITLE
Bumped into 400 error without body when tried to use on Client side 

### ISSUE THREAD

**Issue by MikeKoval** [logdna/nodejs#52]
Hi!

Documentation says that I can use lib in browser, right?

My code looks like:

```
import Logger from 'logdna';
...
const logger = Logger.createLogger(token, {
  hostname: 'ClientSideTest',
  app: 'test',
});
logger.log('Hello LogDNA Test ', { meta: { sequence: 1 } });
```

On network tab of Chrome dev tools I see OPTIONS request with status=200 and another request with status=400 and without response body, so I do not have idea what I did wrongly... 
https://prnt.sc/nstdxd

I would like to notify that these code is used in react app and it's built with webpack.

Can you help me, please?

**Comment by Jaskaranbir** [comment]
Provided your _API Ingestion Key_ is correct, I think you might have to add `localhost:3000` to whitelisted domains [here](https://app.logdna.com/manage/profile).

**Comment by MikeKoval** [comment]
yes, it worked, thank you :+1:
