### ISSUE TITLE
Client Side for IE11

### ISSUE THREAD

**Issue by MikeKoval** [logdna/nodejs#55]
Documentation says that I only need to run `browserify main.js -o bundle.js` to make it working in browser. And really when I did it and added my domain to white list (https://github.com/logdna/nodejs/issues/52) it started working fine in Chrome. 

But then I realized that it's not working in IE11 (arrow functions issue), I've spent much time to make logger work in IE11, that's why I decided to add this here.
1. Run `npm i babelify @babel/core @babel/cli @babel/preset-env` in `node_modules/logdna`
2. Add this to package.json
```
"browserify": {
    "transform": [
      [
        "babelify",
        {
          "presets": [
            [
              "@babel/preset-env",
              {
                "targets": {
                  "browsers": [
                    ">1%",
                    "last 4 versions",
                    "Firefox ESR",
                    "not ie < 11"
                  ]
                }
              }
            ]
          ]
        }
      ]
    ]
  }
```
3. `npm i -g browserify`
4. `browserify index.js --standalone Logger -o bundle.js` - after this lodna object will be available by window.Logger.

P. S. Sorry if I wrote it in wrong place

**Comment by smusali** [comment]
@MikeKoval thanks for the note!
