### ISSUE TITLE
Does console.log with messages!

### ISSUE THREAD

**Issue by grassick** [logdna/nodejs#6]
The exclamation mark is because I ended up with over 1GB of log files on the server which left unchecked would have eventually used up all disk space had I not noticed. I think the console.log statements should be removed from the winston code.

**Comment by respectus** [comment]
So sorry for the issue! I have resolved this and removed the unnecessary statements. I have updated the npm module accordingly. Please let me know if Winston logging is working the way you expect. Sorry for bombarding your server with logs!
