### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by tjoskar** [logdna/nodejs#68]
Hi,

I'm using this module with typescript but since there is no typescript definition file I had to create my own:
```ts
declare module "logdna" {
  interface Options {
    app?: string,
    hostname?: string,
    env?: string,
    index_meta?: boolean,
    ip?: string,
    level?: 'Debug' | 'Trace' | 'Info' | 'Warn' | 'Error' | 'Fatal',
    mac?: string,
    max_length?: boolean,
    timeout?: number,
    with_credentials?: boolean
  }
  interface LogOptions extends Options {
    meta?: Object
  }
  export interface LogDna {
    log: (line: string, options?: LogOptions) => void;
  }

  export function createLogger(key: string, options?: Options): LogDna;
  export function flushAll(): void;
  export function cleanUpAll(): void;
}
```
Is this something you want to add in to this project?

This can easily be done by creating a new file in this project `types.d.ts` and then add `types: "types.d.ts"` in `package.json`.

I can create a PR if you want.

**Comment by andkon** [comment]
Thanks for posting this issue @tjoskar! I've added it to our backlog; if would you be willing to make a PR with those pieces, that'd be much appreciated, as when this comes up to work on on our side, we'll also incorporate this into our CI/CD to make sure it's testable and maintainable in future releases.

**Comment by tjoskar** [comment]
> we'll also incorporate this into our CI/CD to make sure it's testable and maintainable in future releases.

Do you have any plan of doing so? One option could be to just add a `test.ts` file for testing the types, another option could be to rewrite the tests in typescript and another option could be to rewrite the whole lib in typescript. I can gladly help you in any way if needed.

**Comment by zelias500** [comment]
Recently installed this package via NPM, but it appears as though the types file is not included in the distributed node module package. I can work around this for now, but it's likely to cause issues during CI/CD processes down the line.

Can you guys update the available NPM package to include the types declaration :) ?

**Comment by smusali** [comment]
@zelias500 @tjoskar, we have just released [the newest version](https://www.npmjs.com/package/logdna) containing `typescript` support (i.e. including types declaration).
