### ISSUE TITLE
Log metadata from different lines being merged

### ISSUE THREAD

**Issue by elsbree** [logdna/nodejs#69]
Since we installed the most recent version of this library, we've been seeing metadata from log lines getting merged (see [issue on logdna-winston](https://github.com/logdna/logdna-winston/issues/12)). I believe this is due to [this](https://github.com/logdna/nodejs/commit/d176cd2f887258b47a957920537a5d94ea3357d6#diff-212f63e53d7aa8ed04659d1cabd48137R201) change from #66.

The line that was added is:
```javascript
opts.meta = Object.assign(message.meta, opts.meta);
```

The problem with this is that `message.meta` is a reference to `this._meta` (assigned [here](https://github.com/logdna/nodejs/blob/master/lib/logger.js#L172)), which is the default metadata object for all log lines. So the line above actually merges `opts.meta` into the default metadata object every time the log function is called, causing the default metadata object to grow in size and contain all keys from all previous log lines.

I'll submit a PR for this- I think the easy solution is to change the above line to
```javascript
opts.meta = Object.assign({}, message.meta, opts.meta);
```

**Comment by smusali** [comment]
Thanks, @elsbree, for reporting the bug!

#70 has been merged and the new versions have already been released: [`logdna:v3.3.1`](https://www.npmjs.com/package/logdna), [`logdna-winston:v2.2.3`](https://www.npmjs.com/package/logdna-winston), and [`logdna-bunyan:v1.1.3`](https://www.npmjs.com/package/logdna-bunyan).
