### ISSUE TITLE
Winston dependency

### ISSUE THREAD

**Issue by cwp** [logdna/nodejs#7]
It would be better to have the winston transport be a separate module, so that non-winston-users don't have add it as an indirect dependency.

Please?

**Comment by mikehu** [comment]
We'll work on separating this module out for non-winston users and creating a separate winston module.

**Comment by dlferro** [comment]
Is there an ETA for the 2.0 release?

**Comment by adamreisnz** [comment]
I'd also be keen to know if there's an ETA. I'm looking to implement this in our system soon, and would like to know if I need to hold off and wait for the new version or use the 1.x.x for now.

**Comment by respectus** [comment]
Hi @cwp,

This one has been on the backburner for awhile, these modules should have been split right off the bat. Thanks for keeping up with this module guys, I hope version 2.0.0 satisfies your use cases. Please do let me know if you guys have any issues with version 2.0.0. Happy Logging!

**Comment by cwp** [comment]
Glad to see that 2.0 is on npm! I don't see it here on Github, though. Is it still open source?

**Comment by respectus** [comment]
@cwp It is definitely open source, thanks for the reminder to push the latest changes! Hope the module doesn't give you any issues :)

**Comment by cwp** [comment]
Awesome! Thanks for all your work on this!
