### ISSUE TITLE
Chrome & Safari: Refused to set unsafe header "user-agent"

### ISSUE THREAD

**Issue by mvasigh** [logdna/nodejs#86]
## Description
This library sets the `user-agent` header on each request. In the browser (Chrome and Safari specifically) this triggers an error logged from XHR's `setRequestHeader()` as Chrome and Safari treat `user-agent` as a forbidden header name:

Example (Chrome):
<img width="550" alt="Screen Shot 2019-12-02 at 2 10 14 PM" src="https://user-images.githubusercontent.com/13258203/69991532-7c285e80-150d-11ea-9b95-8cc57812532f.png">

`user-agent` is actually [no longer a forbidden header name](https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_header_name) per spec and this works fine in Firefox, so Chrome and Safari are not spec-compliant in this regard. Also, the XHR still fires successfully, so this error doesn't break anything. However, it is quite annoying/disruptive to see the error messages pile up in the console. 

## Expected behavior 
No errors are logged with outgoing XHR requests

## Current behavior
Each outgoing `XMLHttpRequest` in the browser logs an error emitted from `setRequestHeader` when setting the `user-agent` header.

**Comment by mvasigh** [comment]
I opened a PR that doesn't set `user-agent` altogether in the browser, not sure if this is an adequate solution but it's there in case it is.

**Comment by mtrabelsi** [comment]
it is also making API calls takes longer to finished (due to throwing and catching guess )
